[package]
name = "highway-hero"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
engine = {path="../engine"}
glam = "0.24.2"
image = "0.24.7"
rand = "0.8.5"
winit = "0.28"
